In [1]:
import copy
from Anchors import get_anchors
from pprint import pprint
import numpy as np


def round_list(input_list, decimals=0):
    return [[int(round(value, decimals)) for value in row] for row in input_list]


input_shape = [120, 160]
anchors_size=[24, 59, 86, 113, 141, 168]
img_width = input_shape[1]
img_height = input_shape[0]
anchors = get_anchors(input_shape, anchors_size)  # (x1, y1, x2, y2)
print(anchors)

[[0.         0.         0.0625     0.08333333]
 [0.         0.         0.08379652 0.1117287 ]
 [0.0375     0.         0.1125     0.08333333]
 ...
 [0.34421554 0.08457477 0.65578446 0.91542523]
 [0.11840756 0.33040336 0.88159244 0.66959664]
 [0.37280252 0.         0.62719748 1.        ]]


In [4]:
import numpy as np
import os
import copy

def anchor_from_yxhw2xyxy_less_1(anchor_file):
    anchor_yxhw = anchor_file
    anchor_xyxy = copy.deepcopy(anchor_yxhw)
    for i, i_value in enumerate(anchor_yxhw):   
        anchor_xyxy[i][0] = anchor_yxhw[i][1] - 0.5 * anchor_yxhw[i][3]
        anchor_xyxy[i][1] = anchor_yxhw[i][0] - 0.5 * anchor_yxhw[i][2]
        anchor_xyxy[i][2] = anchor_yxhw[i][1] + 0.5 * anchor_yxhw[i][3]
        anchor_xyxy[i][3] = anchor_yxhw[i][0] + 0.5 * anchor_yxhw[i][2]
        anchor_xyxy[i][0] /= 160
        anchor_xyxy[i][2] /= 160
        anchor_xyxy[i][1] /= 120
        anchor_xyxy[i][3] /= 120
    anchor_boxes = np.minimum(np.maximum(anchor_xyxy, 0.0), 1.0)
    return anchor_boxes


def infer_anchor():
    anchor_path = r"/home/zhangyouan/桌面/zya/NN_net/network/SSD/IMX_681_ssd_mobilenet_git/keras/detection/SSD_ipynb_transfer_callback/sony_detection_anchor_boxes.txt"
    anchor = []
    with open(anchor_path, 'r') as f:
        for line in f:
            anchor.append(line.strip().split(', '))
    for i, i_value in enumerate(anchor):
        for j, j_value in enumerate(i_value):
            try:
                anchor[i][j] = float(anchor[i][j])
            except:
                anchor[i][j] = float(anchor[i][j][0:-1])
    
    yxhw_anchor = anchor
    xyxy_anchor = anchor_from_yxhw2xyxy_less_1(yxhw_anchor)  # original anchor is yxhw
    print(xyxy_anchor)
    # return xyxy_anchor

infer_anchor()

[[0.         0.         0.05       0.0875    ]
 [0.         0.         0.06875    0.125     ]
 [0.03125    0.         0.09375    0.0875    ]
 ...
 [0.         0.27083333 0.840625   0.79583333]
 [0.253125   0.         0.546875   1.        ]
 [0.121875   0.04166667 0.678125   1.        ]]
