In [2]:
import cv2 as cv
import os
from PIL import Image
import numpy as np

In [10]:
if __name__ == "__main__":
    file_dir = r"C:\Users\7000031151\Desktop\zya\IMX681\01_Experiments\Datasets\gesture1_open_world"
    w_file_dir = r"C:\Users\7000031151\Desktop\zya\IMX681\01_Experiments\Datasets\gesture1_open_world_slice"
    f = os.listdir(file_dir)
    print(f)
    
    for i in f:
        f_p = file_dir +"/" + i
        src = cv.imread(f_p, 0)
#         print(np.shape(src))
        new = src[2:122]
#         print(np.shape(new))
        new = np.array([x[4:164] for x in new ])
#         print(np.shape(new))
        new = Image.fromarray(new)
        
        new.save(w_file_dir + "/" + i[:-4] + ".jpg")
    

['230803_151815_00000.bmp', '230803_151815_00001.bmp', '230803_151816_00002.bmp', '230803_151817_00003.bmp', '230803_151817_00004.bmp', '230803_151818_00005.bmp', '230803_151818_00006.bmp', '230803_151819_00007.bmp', '230803_151819_00008.bmp', '230803_151820_00009.bmp', '230803_151820_00010.bmp', '230803_151821_00011.bmp', '230803_151822_00012.bmp', '230803_151822_00013.bmp', '230803_151823_00014.bmp', '230803_151824_00015.bmp', '230803_151825_00016.bmp', '230803_151825_00017.bmp', '230803_151826_00018.bmp', '230803_151826_00019.bmp', '230803_151827_00020.bmp', '230803_151827_00021.bmp', '230803_151828_00022.bmp', '230803_151828_00023.bmp', '230803_151829_00024.bmp', '230803_151830_00025.bmp', '230803_151830_00026.bmp', '230803_151831_00027.bmp', '230803_151831_00028.bmp', '230803_151832_00029.bmp', '230803_151833_00030.bmp', '230803_151833_00031.bmp', '230803_151834_00032.bmp', '230803_151834_00033.bmp', '230803_151835_00034.bmp', '230803_151835_00035.bmp', '230803_151836_00036.bmp', 

In [18]:
img = cv.imread("C:/Users/7000031151/Desktop/1/a/a_1.bmp", 0)
print(img)

[[18  0  1 ...  0  0  0]
 [18  0  1 ...  0  0  0]
 [42  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
